### ISSUE TITLE
Main függvények a rendező osztályokban nem használtak

### ISSUE THREAD

**Issue by drecouse** [BME-MIT-IET/csapat-iet-2018#11]
Szerintem meg kéne szüntetni a függvényeket, és tartalmukat komment-be áthelyezni mint használati minta.

**Comment by LikvidJozsi** [comment]
Igen, szerintem is jó ötlet.

**Comment by drecouse** [comment]
CombSort kimaradt

**Comment by juhosattila** [comment]
Valószínűleg, korábbi tesztekhez használták őket. Nem lényegesek az üzleti logika szempontjából. Ki kell tényleg venni őket.

**Comment by nxxxs** [comment]
Rendben van, ki lettek véve.
