### ISSUE TITLE
comb_sort.java fajlban statikus hibák 

### ISSUE THREAD

**Issue by LikvidJozsi** [BME-MIT-IET/csapat-iet-2018#2]
**Details:**

A checkstyle statikus kód-ellenőrző a következő hibákat jelezte a fájlal kapcsolatban:
```
The name of the outer type and the file do not match. [OuterTypeFilename]
Missing a Javadoc comment. [JavadocMethod]
Member name 'a' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [MemberName]
Each variable declaration must be in its own statement. [MultipleVariableDeclarations]
'gap' has incorrect indentation level 8, expected level should be 12. [Indentation]
```
**Javaslom:**
- javadoc komment hozzáadását
- a java fájl nevét módosítsuk a benen található class nevére
- az a változónak beszédesebb név adása: elements
- minden deklariáció külön statementbe szedése

**Comment by drecouse** [comment]
A hibák valóban ki lettek javítva: a kód átláthatóbb és érthetőbb lett.
