### ISSUE TITLE
Maven build rendszer fel konfigurálása

### ISSUE THREAD

**Issue by drecouse** [BME-MIT-IET/csapat-iet-2018#4]
Maven segítségével könnyebb lesz build-elni, és egység teszteket írni.

**Comment by drecouse** [comment]
Alap pom.xml hozzáadása 
be44a40f6d0dd965904d9c396dcdb8fddb18100e

**Comment by juhosattila** [comment]
Gyerek pom.xml összerakva és megfelelő hivatkozások a szülő- és gyerek- pom.xml-ek között megírva. Tesztelni kell.
9fa37abfb6e0e1b41c19d09d4bdab56e5d45c485

**Comment by drecouse** [comment]
pom.xml hibák javítása és összekötése travis-al.
cbe37dc494bddf897341407510d3f62849cf5454

**Comment by nxxxs** [comment]
Rendben, zökkenőmentesen működik.
