### ISSUE TITLE
InsertionSort-osztály tesztelése

### ISSUE THREAD

**Issue by juhosattila** [BME-MIT-IET/csapat-iet-2018#5]
Az `InsertionSort`-osztályt kellene egységtesztelni. Javasolom, hogy készítsünk hozzá JUnit-egységteszteket.

**Comment by juhosattila** [comment]
Sikerült tesztet gyártani. Jól működik az `InsertionSort`.

166aeac373da513df4b8216023df54352a90dab2

**Comment by nxxxs** [comment]
Valóban sikerült, és a lefedettség is magas.
![image](https://user-images.githubusercontent.com/31653297/39436028-29f176ea-4c9d-11e8-935d-cdbd6d5481ce.png)
