### ISSUE TITLE
CombSort-osztály tesztelése

### ISSUE THREAD

**Issue by drecouse** [BME-MIT-IET/csapat-iet-2018#7]
Az `CombSort`-osztályt kellene egység tesztelni. Javasolom, hogy készítsünk hozzá JUnit-egységteszteket.

**Comment by LikvidJozsi** [comment]
Megcsináltam a teszt osztályt 
b87d0807cbf7eb2f5c553cd19ca703969cb85a97

**Comment by LikvidJozsi** [comment]
Fixáltam elnevezésbeli problémákat
cb8b792f4ee62a6c6aa8348e526e7eaf36de1eef

**Comment by nxxxs** [comment]
Rendben van.
