### ISSUE TITLE
Kódlefedettség vizsgáló rendszer konfigurálása

### ISSUE THREAD

**Issue by drecouse** [BME-MIT-IET/csapat-iet-2018#8]
Javaslom a `codecov.io` használatát mivel könnyen integrálható a `Travis`-szal.

**Comment by nxxxs** [comment]
Elkészült.
45f01608dd7ef530572ec74f26278dd3242edf8a
![image](https://user-images.githubusercontent.com/31653297/39433528-616a29fc-4c96-11e8-8b3d-a7e455f72566.png)
