### ISSUE TITLE
CircleSort-osztály tesztelése 

### ISSUE THREAD

**Issue by drecouse** [BME-MIT-IET/csapat-iet-2018#9]
Az `CircleSort`-osztályt kellene egység tesztelni. Javasolom, hogy készítsünk hozzá JUnit-egységteszteket.

**Comment by nxxxs** [comment]
Rendben van. 25ec8a69fd360373c96fc0c2bc5520289a481fc4

**Comment by LikvidJozsi** [comment]
Lérehoztam a tesztet.

**Comment by juhosattila** [comment]
A CircleSort-oszt'ly lefedettsége alacsony, ezért újabb egységtesztre van szükség.

**Comment by nxxxs** [comment]
Rendben van, megnövekedett a lefedettség.
![image](https://user-images.githubusercontent.com/31653297/39435864-c5d0c184-4c9c-11e8-928a-45d4f01c072a.png)
